name: 'PolymerHighchartsTest'
version: 0.0.1
description: >
  A starter template for a polymer.dart web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  polymer: '>=0.15.0 <0.16.0'
  core_elements: any
  #polymer_highcharts: '0.2.1+1'
  polymer_highcharts:  
    path: C:\trabajos\conento\dart\polymer_highcharts
  highcharts_options: '>=0.2.1+2 <0.3.0' 
transformers:
- polymer:
    entry_points: web/index.html
    inline_stylesheets:
      lib/css/sample.css: false
